const $=id=>document.getElementById(id);const state={server:localStorage.getItem('mousey.server')||'',pin:localStorage.getItem('mousey.pin')||'',connected:false,motion:false,sensitivity:1.2,invert:false,last:null,scroll:false};$('server').value=state.server;$('pin').value=state.pin;
function endpoint(){let s=$('server').value.trim();if(!s)return null;if(!/^https?:\/\//i.test(s))s='http://'+s;return s.replace(/\/$/,'')+'/';}
async function send(action,extra={}){if(!state.connected)return;const url=endpoint();if(!url)return;try{await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:state.pin,action,...extra}),cache:'no-store'});}catch(e){setMessage('Connection lost — check that the PC is on the same Wi-Fi.','error');disconnect(false)}}
function setMessage(t,c=''){const m=$('message');m.textContent=t;m.className='message '+c}
async function connect(){state.server=$('server').value.trim();state.pin=$('pin').value.trim();if(!state.server||state.pin.length!==6){setMessage('Enter the PC address and 6-digit PIN.','error');return}localStorage.setItem('mousey.server',state.server);localStorage.setItem('mousey.pin',state.pin);try{let url=endpoint();let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:state.pin,action:'ping'}),cache:'no-store'});if(!r.ok)throw new Error('bad pin');state.connected=true;$('connectView').classList.add('hidden');$('mouseView').classList.remove('hidden');$('statusText').textContent='Connected';setMessage('','');if(!state.motion)await requestMotion();}catch(e){setMessage('Could not connect. Check the address, PIN and Wi-Fi.','error')}}
async function requestMotion(){if(!('DeviceMotionEvent'in window)){setMessage('Motion sensors are not available in this browser.','error');return false}try{if(typeof DeviceMotionEvent.requestPermission==='function'){const p=await DeviceMotionEvent.requestPermission();if(p!=='granted')throw new Error('denied')}window.addEventListener('devicemotion',onMotion,{passive:true});state.motion=true;setMessage('Motion control enabled','ok');return true}catch(e){setMessage('Tap “Enable motion control” and allow Motion access.','error');return false}}
function onMotion(e){if(!state.connected||state.scroll)return;const a=e.rotationRate;if(!a)return;let x=Number(a.gamma??0),y=Number(a.alpha??0);if(!Number.isFinite(x)||!Number.isFinite(y))return;const s=state.sensitivity*0.72;send('move',{dx:Math.max(-100,Math.min(100,x*s)),dy:Math.max(-100,Math.min(100,(state.invert?-y:y)*s))})}
$('connectBtn').addEventListener('click',connect);$('motionBtn').addEventListener('click',requestMotion);
let scrollLast=0;let touchStart=null;function pressZone(btn){btn.classList.add('active');send('down',{button:btn.dataset.button})}function releaseZone(btn){btn.classList.remove('active');send('up',{button:btn.dataset.button})}
document.querySelectorAll('.click-zone').forEach(btn=>{let timer=null,drag=false;btn.addEventListener('touchstart',e=>{e.preventDefault();if(e.touches.length!==1)return;timer=setTimeout(()=>{drag=true;pressZone(btn)},230)},{passive:false});btn.addEventListener('touchend',e=>{e.preventDefault();clearTimeout(timer);if(drag){releaseZone(btn);drag=false}else send('click',{button:btn.dataset.button})},{passive:false});btn.addEventListener('touchcancel',()=>{clearTimeout(timer);if(drag){releaseZone(btn);drag=false}})});
$('pad').addEventListener('touchstart',e=>{if(e.touches.length===2){state.scroll=true;touchStart={y:(e.touches[0].clientY+e.touches[1].clientY)/2};$('mouseView').classList.add('scrolling')}},{passive:true});$('pad').addEventListener('touchmove',e=>{if(!state.scroll||e.touches.length!==2)return;const y=(e.touches[0].clientY+e.touches[1].clientY)/2;if(touchStart!==null){const dy=(y-touchStart)/30;if(Math.abs(dy)>.15){send('scroll',{dy:-dy});touchStart=y}}},{passive:true});$('pad').addEventListener('touchend',e=>{if(e.touches.length<2){state.scroll=false;touchStart=null;$('mouseView').classList.remove('scrolling')}},{passive:true});
$('centerBtn').addEventListener('click',()=>{setMessage('Recenter by holding the phone flat, then continue moving.','ok');setTimeout(()=>setMessage(''),2200)});$('scrollBtn').addEventListener('click',()=>{state.scroll=!state.scroll;$('mouseView').classList.toggle('scrolling',state.scroll);$('scrollBtn').querySelector('span').textContent=state.scroll?'Scroll on':'Scroll'});$('disconnectBtn').addEventListener('click',()=>disconnect(true));function disconnect(show=true){state.connected=false;$('mouseView').classList.add('hidden');$('connectView').classList.remove('hidden');if(show)setMessage('Disconnected');}
$('settingsBtn').addEventListener('click',()=>$('settings').classList.remove('hidden'));$('closeSettings').addEventListener('click',()=>$('settings').classList.add('hidden'));$('sensitivity').addEventListener('input',e=>state.sensitivity=Number(e.target.value));$('invertBtn').addEventListener('click',()=>{state.invert=!state.invert;$('invertBtn').textContent=state.invert?'On':'Off'});
if(location.protocol!=='https:'&&location.hostname!=='localhost'){setMessage('For iPhone motion control, open this site over HTTPS.','error')}
